# Generated by Django 2.1.7 on 2019-03-02 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0003_auto_20190302_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Product name')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=['https://placehold.it/500X500'], max_length=255, verbose_name='Image URI'), size=None)),
                ('description', models.TextField(verbose_name='Product description')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('-created_at',),
            },
        ),
    ]
