# Generated by Django 2.1.7 on 2019-02-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='activation token'),
        ),
    ]
