# Generated by Django 2.1.7 on 2019-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='verification token'),
        ),
    ]
