# Generated by Django 2.1.7 on 2019-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190218_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password reset token'),
        ),
    ]
